### ISSUE TITLE
Issue personale come TODO per Chronos

### ISSUE THREAD

**Issue by mdipirro** [BugBusterSWE/documentation#68]
- [x] Riaggiungere supporto da terminale
- [x] Incorporare GUI plugin in GUI principale
- [x] Lista plugin e moduli installati

**Comment by Polpetta** [comment]
Ma questa issue non andrebbe in Chronos? :sweat_smile:

**Comment by mdipirro** [comment]
è vero
